# Generated by Django 5.0.6 on 2024-07-01 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marca',
            fields=[
                ('idMarca', models.IntegerField(primary_key=True, serialize=False, verbose_name='idMarca')),
                ('nombreMarca', models.CharField(max_length=150, verbose_name='nombreMarca')),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('idVehiculo', models.IntegerField(primary_key=True, serialize=False, verbose_name='idVehiculo')),
                ('nombreVehiculo', models.CharField(max_length=150, verbose_name='nombreVehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('idSolicitud', models.IntegerField(primary_key=True, serialize=False, verbose_name='idSolicitud')),
                ('nombreSolicitud', models.CharField(max_length=50, verbose_name='NombreSolicitud')),
                ('detalles', models.CharField(blank=True, max_length=300, null=True, verbose_name='detallesSolicutud')),
                ('imagen', models.ImageField(default='nn.jpg', upload_to='images/', verbose_name='Imagen')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.marca')),
                ('Vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.vehiculo')),
            ],
        ),
    ]
