# Generated by Django 5.0.6 on 2024-07-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Solicitud',
            old_name='Vehiculo',
            new_name='vehiculo',
        ),
    ]
