# Generated by Django 5.0.6 on 2024-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_vehiculo_solicitud_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='imagen',
            field=models.ImageField(default='nn.jpg', upload_to='img/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombreSolicitud',
            field=models.CharField(max_length=50, verbose_name='nombreSolicitud'),
        ),
    ]
